//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vobsoft.net.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$(AssemblyLocation)\\NetworkTraffic.json")]
        public string Logfile {
            get {
                return ((string)(this["Logfile"]));
            }
            set {
                this["Logfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public double Interval {
            get {
                return ((double)(this["Interval"]));
            }
            set {
                this["Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\GitHub\\NetworkTrafficLogger\\NetworkTrafficLogger\\NetworkTraffic.s3db")]
        public string Logfile2 {
            get {
                return ((string)(this["Logfile2"]));
            }
            set {
                this["Logfile2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.116.128\\d\\GitHub\\NetworkTrafficLogger\\NetworkTrafficLogger\\NetworkTraff" +
            "ic.s3db")]
        public string Logfile3 {
            get {
                return ((string)(this["Logfile3"]));
            }
            set {
                this["Logfile3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\adbrvo0\\source\\repos\\NetworkTrafficLogger\\NetworkTrafficLogger\\NetworkTr" +
            "affic.s3db")]
        public string Logfile4 {
            get {
                return ((string)(this["Logfile4"]));
            }
            set {
                this["Logfile4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.116.128\\d\\GitHub\\NetworkTrafficLogger\\NetworkTrafficLogger\\NetworkTraff" +
            "ic.json")]
        public string Logfile5 {
            get {
                return ((string)(this["Logfile5"]));
            }
            set {
                this["Logfile5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U:\\github\\NetworkTrafficLogger\\NetworkTrafficLogger\\NetworkTraffic.json")]
        public string Logfile6 {
            get {
                return ((string)(this["Logfile6"]));
            }
            set {
                this["Logfile6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InstantWrite {
            get {
                return ((bool)(this["InstantWrite"]));
            }
            set {
                this["InstantWrite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\github\\NetworkTrafficLogger\\NetworkTrafficLogger\\NetworkTraffic.json")]
        public string Logfile7 {
            get {
                return ((string)(this["Logfile7"]));
            }
            set {
                this["Logfile7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$(AssemblyLocation)\\NetworkTraffic.json")]
        public string Logfile8 {
            get {
                return ((string)(this["Logfile8"]));
            }
            set {
                this["Logfile8"] = value;
            }
        }
    }
}
