//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkTrafficMonitor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Bommel\\Documents\\GitHub\\NetworkTrafficLogger\\NetworkAdapterTest\\bin\\Debu" +
            "g\\NetworkTraffic.json")]
        public string Logfile {
            get {
                return ((string)(this["Logfile"]));
            }
            set {
                this["Logfile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowActiveAdaptersOnly {
            get {
                return ((bool)(this["ShowActiveAdaptersOnly"]));
            }
            set {
                this["ShowActiveAdaptersOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\192.168.116.128\\d\\GitHub\\NetworkTrafficLogger\\NetworkAdapterTest\\bin\\Debug\\Netw" +
            "orkTraffic.json")]
        public string Logfile1 {
            get {
                return ((string)(this["Logfile1"]));
            }
            set {
                this["Logfile1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Bommel\\Documents\\GitHub\\NetworkTrafficLogger\\NetworkAdapterTest\\bin\\Debu" +
            "g")]
        public string Logfile2 {
            get {
                return ((string)(this["Logfile2"]));
            }
            set {
                this["Logfile2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U:\\GitHub\\NetworkTrafficLogger\\NetworkAdapterTest\\bin\\Debug\\NetworkTraffic.json")]
        public string Einstellung {
            get {
                return ((string)(this["Einstellung"]));
            }
            set {
                this["Einstellung"] = value;
            }
        }
    }
}
